### ISSUE TITLE
format instructions as md

### ISSUE THREAD

**Issue by annefou** [arockenberger/historicalrecipes#4]
Hei,

I think it would be nice to have a substantial change on instructions.txt.

I would like to move to markdown as it would be so much nicer.

What do you think?

**Comment by annefou** [comment]
@arockenberger Could you have a look please?

**Comment by arockenberger** [comment]
Sounds great! Do you want to do it?

**Comment by annefou** [comment]
Cool! Yes I can do it! Thank you. I'll make a pull request asap.
